version: "3.7"

services:
  reactfront:
    container_name: reactv07
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  rasabot:
    build: ./rasa
    container_name: rasa
    restart: always
    ports:
      - “5000:5000”
